### ISSUE TITLE
Log activity on create

### ISSUE THREAD

**Issue by SarahCordeau** [Locastic/Loggastic#11]
On create action `currentValues` are not saved.

It's possible to change `ActivityLogProcessor::processCreatedItem` with:

```
        $changes = ArraysComparer::getCompared($normalizedItem, []);
        if (!$changes && !$message->isCreateLogWithoutChanges()) {
            return;
        }
        // create log for item creation
        $activityLog = $this->activityLogInputFactory->createFromActivityLogMessage($message, $changes);
```

**Comment by paullla** [comment]
hey @SarahCordeau, this is the default behaviour for create action. But if you want to have it saved, you can decorate `ActivityLogProcessor` with the code you did here and it will work that way for you.

**Comment by SarahCordeau** [comment]
OK Thanks, I closed the issue.
