### ISSUE TITLE
Incorrect minimum PHP(>=8.0) version in composer.json

### ISSUE THREAD

**Issue by jacyimp** [Locastic/Loggastic#21]
## Problem
The minimum PHP version should be 8.1 since you're using read-only properties in some places such as "Locastic\Loggastic\Event\PreDispatchActivityLogMessageEvent"

## Changes
I think you should edit `composer.json` to use PHP 8.1 instead.

**Comment by paullla** [comment]
@jacyimp thank you for reporting, it's fixed by https://github.com/Locastic/Loggastic/pull/23 :)
